# Generated by Django 4.0.3 on 2022-03-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arwin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='addrs',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.IntegerField(blank=True, default=1, max_length=14),
            preserve_default=False,
        ),
    ]
