# Generated by Django 4.0.3 on 2022-03-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arwin', '0002_alter_skills_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
